#ifndef TEST_UTILS_MSG_TEST_H
#define TEST_UTILS_MSG_TEST_H

void test_atiende_sabotaje_serializar_y_deserializar(void);
void test_desplazamiento_tripulante_serializar_y_deserializar(void);
void test_eliminar_tripulante_serializar_y_deserializar(void);
void test_finalizacion_tripulante_serializar_y_deserializar(void);
void test_informar_sabotaje_serializar_y_deserializar(void);
void test_iniciar_tripulante_serializar_y_deserializar(void);
void test_iniciar_tarea_serializar_y_deserializar(void);
void test_obtener_bitacora_serializar_y_deserializar(void);
void test_proxima_tarea_serializar_y_deserializar(void);
void test_resuelve_sabotaje_serializar_y_deserializar(void);
void test_tripulante_nuevo_estado_serializar_y_deserializar(void);

#endif