#ifndef UTILS_PROTOCOL_OPCODES_H
#define UTILS_PROTOCOL_OPCODES_H

#include "utils/typedefs.h"

typedef enum
{
    OK,
    FAIL,
    DESPLAZAMIENTO_TRIPULANTE,
	BITACORA,
    MOVIMIENTO_TRIPULANTE,
    INFORMAR_SABOTAJE,
    INICIO_TAREA,
    NUEVA_TAREA,
    FINALIZACION_TAREA,
    ATIENDE_SABOTAJE,
    RESUELVE_SABOTAJE,
    OBTENER_BITACORA,
    ELIMINAR_TRIPULANTE,
    INICIAR_TRIPULANTE,
    PROXIMA_TAREA,
    TRIPULANTE_NUEVO_ESTADO,
    FINALIZACION_FSCK
} u_opcode_e;

#define U_MSG_IS_VALID(opcode)\
    ((opcode) >= DESPLAZAMIENTO_TRIPULANTE && (opcode) <= TRIPULANTE_NUEVO_ESTADO)

const char* u_opcode_to_string(u_opcode_e opcode);

#endif
